import streamlit as st
import pandas as pd

from frontend.components.db_connector import fetch_data

st.set_page_config(page_title="Earnings Summaries", layout="wide")

st.title("📄 AI Earnings Summaries")
st.markdown("Summaries generated by **facebook/bart-large-cnn** via HuggingFace Inference API.")

query = """
    SELECT 
        ticker,
        report_date,
        source_file,
        summary,
        created_at
    FROM public.earnings_summaries
    ORDER BY report_date DESC
"""

try:
    df = fetch_data(query)
    
    if df.empty:
        st.info("No earnings summaries found. Upload a PDF to `data/earnings/` and run the pipeline.")
    else:
        # Allow filtering
        companies = ["All"] + list(df['ticker'].unique())
        selected = st.selectbox("Filter by Symbol", companies)
        
        if selected != "All":
            df = df[df['ticker'] == selected]
            
        for _, row in df.iterrows():
            with st.expander(f"{row['ticker']} — {row['report_date']} ({row['source_file']})"):
                st.write(row['summary'])
                st.caption(f"Generated at: {row['created_at']}")
                
except Exception as e:
    st.error(f"Failed to fetch summaries: {e}")
